domain: example.com
url: https://example.com
baseurl: "/wind"

title: Bad Dreams
email: mhead83@gmail.com
author: Bad Dreamer

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "mhead83@gmail.com"
  instagram: "@whereismymatt"
  discord: "https://discord.com/"
